services:
  postgres1:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cloud
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - pg1_data:/var/lib/postgresql/data
    networks:
      - appnet

  postgres2:
    build:
      context: docker/postgresql
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=cloud
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - pg2_data:/var/lib/postgresql/data
    networks:
      - appnet

  java:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres2
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres2:5432/cvicenie_docker?currentSchema=cvicenie_docker
      - SPRING_DATASOURCE_USERNAME=cvicenie_docker
      - SPRING_DATASOURCE_PASSWORD=cvicenie_docker
    depends_on:
      - postgres2
    networks:
      - appnet

  java-build:
    build:
      context: .
      target: build

volumes:
  pg1_data:
  pg2_data:

networks:
  appnet:
