apiVersion: v1
kind: Namespace
metadata:
  name: sb-demo-dd
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: sb-demo-dd
stringData:
  postgres-user: user
  postgres-password: password
  app-db-user: cvicenie_docker
  app-db-password: cvicenie_docker
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: sb-demo-dd
data:
  init.sql: |
    CREATE USER cvicenie_docker WITH PASSWORD 'cvicenie_docker';

    CREATE DATABASE cvicenie_docker WITH ENCODING 'UTF8';

    GRANT ALL PRIVILEGES ON DATABASE cvicenie_docker to cvicenie_docker;

    \connect cvicenie_docker;
    create extension if not exists pg_trgm;
    create extension if not exists unaccent;

    create or replace function public.f_unaccent(text)
      returns text as
    $func$
    select public.unaccent('public.unaccent', $1)
    $func$  language sql immutable;

    create or replace function public.f_normalize(text)
      returns text as
    $func$
    select lower(public.f_unaccent($1))
    $func$  language sql immutable;

    CREATE SCHEMA cvicenie_docker AUTHORIZATION cvicenie_docker;

    CREATE TABLE cvicenie_docker."transaction" (
      transaction_id varchar(255) NOT NULL,
      amount numeric(38, 2) NOT NULL,
      currency varchar(255) NOT NULL,
      description varchar(255) NULL,
      effective_date date NULL,
      constant_symbol varchar(255) NULL,
      payer_reference varchar(255) NULL,
      specific_symbol varchar(255) NULL,
      variable_symbol varchar(255) NULL,
      sender_account_balance_value numeric(38, 2) NULL,
      sender_account_balance_currency varchar(255) NULL,
      sender_account_bic varchar(255) NULL,
      sender_account_iban varchar(255) NULL,
      sender_account_name varchar(255) NULL,
      status varchar(255) NOT NULL,
      target_account_balance_value numeric(38, 2) NULL,
      target_account_balance_currency varchar(255) NULL,
      target_account_bic varchar(255) NULL,
      target_account_iban varchar(255) NULL,
      target_account_name varchar(255) NULL,
      CONSTRAINT transaction_pkey PRIMARY KEY (transaction_id)
    );

    GRANT USAGE ON SCHEMA cvicenie_docker TO cvicenie_docker;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA cvicenie_docker TO cvicenie_docker;

    insert into cvicenie_docker."transaction" (transaction_id, amount, currency, description, effective_date, constant_symbol, payer_reference, specific_symbol, variable_symbol, sender_account_balance_value, sender_account_balance_currency, sender_account_bic, sender_account_iban, sender_account_name, status, target_account_balance_value, target_account_balance_currency, target_account_bic, target_account_iban, target_account_name) values ('5ae57f2a-5296-4643-876b-da3d5532feb2', 42, 'EUR', 'Anvil', '2022-09-24', null, null, null, '123456', 958, 'EUR', null, 'SK8975000000000012345671', null, 'PROCESSED', null, null, 'DEUTDEFFXXX', 'DE89370400440532013000', 'Acme corp.');
    insert into cvicenie_docker."transaction" (transaction_id, amount, currency, description, effective_date, constant_symbol, payer_reference, specific_symbol, variable_symbol, sender_account_balance_value, sender_account_balance_currency, sender_account_bic, sender_account_iban, sender_account_name, status, target_account_balance_value, target_account_balance_currency, target_account_bic, target_account_iban, target_account_name) values ('6fdd23ca-abd3-40e7-8e3d-ecec2ec80036', 12, 'EUR', 'Cashback', '2022-09-25', null, null, null, null, null, null, 'DEUTDEFFXXX', 'DE89370400440532013000', 'Acme corp.', 'PROCESSED', 970, 'EUR', null, 'SK8975000000000012345671', null);
    insert into cvicenie_docker."transaction" (transaction_id, amount, currency, description, effective_date, constant_symbol, payer_reference, specific_symbol, variable_symbol, sender_account_balance_value, sender_account_balance_currency, sender_account_bic, sender_account_iban, sender_account_name, status, target_account_balance_value, target_account_balance_currency, target_account_bic, target_account_iban, target_account_name) values ('a77faf16-7a19-45ea-b625-9587701510e2', 10, 'EUR', 'Cashback', '2022-09-26', null, null, null, null, null, null, 'DEUTDEFFXXX', 'DE89370400440532013000', 'Acme corp.', 'PROCESSED', 1010, 'EUR', null, 'SK3112000000198742637541', null);
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: sb-demo-dd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: sb-demo-dd
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
        - name: postgres-init
          configMap:
            name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: sb-demo-dd
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-demo
  namespace: sb-demo-dd
spec:
  selector:
    matchLabels:
      app: sb-demo
  template:
    metadata:
      labels:
        app: sb-demo
    spec:
      containers:
        - name: sb-demo
          image: sb-demo:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: postgres2
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/cvicenie_docker?currentSchema=cvicenie_docker
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: app-db-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: app-db-password
---
apiVersion: v1
kind: Service
metadata:
  name: sb-demo
  namespace: sb-demo-dd
spec:
  type: LoadBalancer
  selector:
    app: sb-demo
  ports:
    - port: 8080
      targetPort: 8080
