minimal.fee.limit=${minimal_fee_limit}
%dev.minimal.fee.limit=10000
%test.minimal.fee.limit=10000

quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=${db_url}
%dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:test
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:test
quarkus.datasource.username=${db_username}
%dev.quarkus.datasource.username=sa
%test.quarkus.datasource.username=sa

#drop-and-create
%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create


quarkus.swagger-ui.always-include=true


quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
%dev.quarkus.security.users.embedded.users.admin-user=admin-password
%test.quarkus.security.users.embedded.users.admin-user=admin-password
%prod.quarkus.security.users.embedded.users.admin-user=${user_password}
quarkus.security.users.embedded.roles.admin-user=user,admin

quarkus.container-image.group=fmfi
quarkus.container-image.name=fee-service
quarkus.container-image.tag=latest
quarkus.container-image.push=false

quarkus.kubernetes.env.configmaps=app-configmap
quarkus.kubernetes.env.secrets=app-secret
quarkus.kubernetes.image-pull-policy=never
quarkus.kubernetes.service-type=load-balancer
quarkus.kubernetes.ports."http".host-port=8084
quarkus.kubernetes.replicas=2
quarkus.kubernetes.liveness-probe.initial-delay=0S
quarkus.kubernetes.liveness-probe.period=5S
quarkus.kubernetes.liveness-probe.timeout=5S
quarkus.kubernetes.readiness-probe.initial-delay=0S
quarkus.kubernetes.readiness-probe.period=10S
quarkus.kubernetes.readiness-probe.timeout=10S

quarkus.kubernetes.namespace=default
quarkus.kubernetes-client.trust-certs=true
quarkus.kubernetes-client.api-server-url=https://kubernetes.docker.internal:6443/
quarkus.kubernetes-client.client-cert-data=${CLIENT_CERT_DATA:}
quarkus.kubernetes-client.client-key-data=${CLIENT_CERT_KEY:}
